# Generated by Django 4.0.4 on 2022-05-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License_Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='studentID',
        ),
        migrations.AddField(
            model_name='user_info',
            name='licenseKey',
            field=models.CharField(default='', max_length=50),
        ),
    ]
