# Generated by Django 4.0.4 on 2022-05-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0003_rename_key_license_key_licensekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_key',
            name='licenseKey',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='licenseKey',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
