# Generated by Django 4.0.4 on 2022-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0009_alter_global_label_url_url_alter_label_url_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_cmd_tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=50)),
                ('cmd', models.CharField(default='', max_length=30)),
                ('mdt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
